FROM node:16.13.2-buster-slim
MAINTAINER "Mahesh" "mahesh@ilimi.in"

# Install required packages
RUN apt-get update && apt-get install -y zip

# Create necessary directories
RUN mkdir -p /opt/telemetry

# Copy source code into container
ADD src /opt/telemetry/

# Set working directory
WORKDIR /opt/telemetry/

# Install dependencies
RUN npm install

# Set final working directory
WORKDIR /opt/telemetry/

# Run zip and start the Node.js app
CMD zip -r /opt/telemetry-service.zip /opt/telemetry && node app.js