version: '3.3'
services:
  telemetry-service:
    image: telemetry-mongodb:latest
    ports:
      - "5001:5001"
    environment:
      MONGODB_CONNECTION_URL: mongodb+srv://all-telangana:zxcASD123@cluster0.c2z6a.mongodb.net/telemetry-vapt?retryWrites=true&w=majority&appName=Cluster0
      MONGODB_DATABASE: telemetry
      MONGODB_COLLECTION_PREFIX: all
      telemetry_local_storage_type: mongodb
      telemetry_local_storage_enabled: 'true'
      node_env: prod
      telemetry_service_port: 5001
    networks:
      - all-services

networks:
 all-services:
    driver: bridge